import React, { useState } from 'react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar, Legend } from 'recharts';
import { money } from '../../utils/format';
const shortMoney=value=>`₹${Math.round(value/1000)}k`;
export default function Spending({spending,period}) {
 const [view,setView] = useState('month');
 const data = view==='month' ? spending.daily : spending.monthly.slice(-6);
 const key = view==='month' ? 'amount' : 'expenses';
 return <section className="glass spending-trend"><div className="section-heading"><div><span className="eyebrow">A LITTLE PERSPECTIVE</span><h2>Your money, over time</h2><p>{view==='month' ? `Daily outgoings · ${period.month}` : 'Six completed months of income and outgoings'}</p></div><div className="segmented" aria-label="Chart period"><button aria-pressed={view==='month'} onClick={()=>setView('month')}>1M</button><button aria-pressed={view==='six'} onClick={()=>setView('six')}>6M</button></div></div><div className="chart-area" role="img" aria-label={view==='month'?'Daily spending chart':'Monthly income and spending comparison'}><ResponsiveContainer width="100%" height="100%">{view==='month'?<AreaChart data={data} margin={{top:20,right:10,left:-15,bottom:0}}><defs><linearGradient id="spending-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--accent-blue)" stopOpacity={.35}/><stop offset="100%" stopColor="var(--accent-blue)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="date" tickFormatter={value=>value.slice(-2)} minTickGap={28} tickLine={false} axisLine={false}/><YAxis tickFormatter={shortMoney} tickLine={false} axisLine={false}/><Tooltip formatter={value=>[money(value),'Outgoings']} contentStyle={{background:'var(--tooltip-bg)',border:'1px solid var(--glass-border)',borderRadius:16,color:'var(--text-primary)'}}/><Area type="monotone" dataKey={key} stroke="var(--accent-blue)" strokeWidth={2.5} fill="url(#spending-fill)" isAnimationActive={false}/></AreaChart>:<BarChart data={data} margin={{top:20,right:10,left:-15,bottom:0}}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="month" tickFormatter={value=>new Date(value+'-01T12:00:00').toLocaleDateString('en-IN',{month:'short'})} tickLine={false} axisLine={false}/><YAxis tickFormatter={shortMoney} tickLine={false} axisLine={false}/><Tooltip formatter={money} contentStyle={{background:'var(--tooltip-bg)',border:'1px solid var(--glass-border)',borderRadius:16}}/><Legend/><Bar dataKey="income" name="Income" fill="var(--accent-cyan)" radius={[4,4,0,0]} isAnimationActive={false}/><Bar dataKey="expenses" name="Outgoings" fill="var(--accent-blue)" radius={[4,4,0,0]} isAnimationActive={false}/></BarChart>}</ResponsiveContainer></div><details className="chart-data"><summary>View chart data</summary><div className="chart-data-list">{data.map(row=><div key={row.date||row.month}><span>{row.date||row.month}</span><span>{view==='month'?money(row.amount):`Income ${money(row.income)} · Outgoings ${money(row.expenses)}`}</span></div>)}</div></details></section>;
}
