import React,{useEffect,useState} from 'react';
import {Bell,ChevronDown,ShieldAlert,Sparkles} from 'lucide-react';
import DataState from '../components/common/DataState';
import {getAlerts,updateAlert} from '../services/api';

export default function Alerts(){
 const [data,setData]=useState(null),[status,setStatus]=useState('loading'),[attempt,setAttempt]=useState(0),[actionError,setActionError]=useState('');
 useEffect(()=>{let active=true;const controller=new AbortController();setStatus('loading');getAlerts({signal:controller.signal}).then(value=>{if(active){setData(value);setStatus('ready')}}).catch(()=>{if(active)setStatus('error')});return()=>{active=false;controller.abort()}},[attempt]);
 const act=async(id,action)=>{setActionError('');try{await updateAlert(id,action);setAttempt(n=>n+1)}catch(error){setActionError(error.message)}};
 return <><div className="page-heading"><div><span className="eyebrow">PROACTIVE SUPPORT</span><h1>Saathi Alerts</h1><p>Early signals, clear evidence, and empathetic next steps.</p></div><Bell/></div>
 {status!=='ready'?<DataState status={status==='error'?'error':'loading'} retry={()=>setAttempt(n=>n+1)}/>:<><div className="alert-headline glass"><span className="round-icon"><Bell/></span><div><strong>{data.unread_count} unread</strong><p>Generated from your verified financial and transaction patterns.</p></div></div>{actionError&&<p className="form-message">{actionError}</p>}<section className="experience-stack">{data.alerts.map(alert=><details className={`glass action-alert severity-${alert.severity.toLowerCase()}`} key={alert.alert_id}><summary><span className="severity-badge">{alert.severity}</span><div><strong>{alert.title}</strong><small>{alert.type.replaceAll('_',' ')} · {alert.status}</small></div><ChevronDown/></summary><div className="action-alert-body"><p>{alert.message}</p><div className="why-panel"><strong>Why this matters</strong><p>{alert.why_it_matters}</p><ul>{alert.evidence.map(item=><li key={item}>{item}</li>)}</ul></div><strong>What Saathi recommends</strong><p>{alert.recommended_action}</p>{alert.safer_alternative&&<p className="safer-copy"><Sparkles size={15}/>{alert.safer_alternative}</p>}<div className="alert-actions">{alert.status==='UNREAD'&&<button onClick={()=>act(alert.alert_id,'read')}>Mark as read</button>}{alert.type==='FRAUD_RISK'&&<><button onClick={()=>act(alert.alert_id,'mine')}>This was me</button><button className="danger-button" onClick={()=>act(alert.alert_id,'report')}><ShieldAlert size={15}/>Report suspicious</button></>}<button onClick={()=>act(alert.alert_id,'dismiss')}>Dismiss</button></div><small>{alert.source_engine} · Prototype guidance; fraud alerts are not proof.</small></div></details>)}{!data.alerts.length&&<div className="glass alert-empty"><strong>No proactive alerts right now</strong><p>Your verified patterns do not currently trigger an intervention.</p></div>}</section><p className="demo-disclaimer">{data.methodology}</p></>}
 </>;
}
