import React,{useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,Landmark,MessageCircle,TriangleAlert} from 'lucide-react';
import {Link} from 'react-router-dom';
import DataState from '../components/common/DataState';
import {assessLoanJourney,startLoanJourney} from '../services/api';
import {money} from '../utils/format';

export default function LoanJourney(){
 const [context,setContext]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 const [form,setForm]=useState({loan_amount:200000,purpose:'Business',annual_interest_rate:8,tenure_months:12});
 useEffect(()=>{let active=true;const controller=new AbortController();setError('');startLoanJourney({signal:controller.signal}).then(data=>{if(active)setContext(data)}).catch(err=>{if(active)setError(err.message)});return()=>{active=false;controller.abort()}},[attempt]);
 const update=e=>setForm(current=>({...current,[e.target.name]:e.target.value}));
 const submit=async e=>{e.preventDefault();setError('');try{setResult(await assessLoanJourney({...form,loan_amount:Number(form.loan_amount),annual_interest_rate:Number(form.annual_interest_rate),tenure_months:Number(form.tenure_months)}))}catch(err){setError(err.message)}};
 if(!context)return <DataState status={error?'error':'loading'} retry={()=>setAttempt(value=>value+1)}/>;
 const known=context?.known_financial_context;
 return <><div className="page-heading"><div><span className="eyebrow">FINANCIAL SUITABILITY GUIDANCE</span><h1>Borrow with context.</h1><p>Known financial details are reused—only the new loan scenario is requested.</p></div><Landmark/></div>
 <div className="journey-progress loan-progress"><span className="active">1 Loan need</span><span className="active">2 Amount</span><span className="active">3 Purpose</span><span className="active">4 Financial context</span><span className={result?'active':''}>5 Loan impact</span><span className={result?'active':''}>6 Guidance</span></div>
 <section className="journey-grid"><form className="glass journey-form" onSubmit={submit}><span className="eyebrow">WHAT ARE YOU CONSIDERING?</span><label>Loan amount (₹)<input name="loan_amount" type="number" min="1" value={form.loan_amount} onChange={update}/></label><label>Purpose<select name="purpose" value={form.purpose} onChange={update}>{context?.purposes.map(item=><option key={item}>{item}</option>)}</select></label><label>Annual interest rate (%)<input name="annual_interest_rate" type="number" min="0" max="100" step=".1" value={form.annual_interest_rate} onChange={update}/></label><label>Tenure<select name="tenure_months" value={form.tenure_months} onChange={update}><option value="12">1 year</option><option value="24">2 years</option><option value="36">3 years</option><option value="60">5 years</option></select></label><button className="primary-button">See financial suitability</button>{error&&<p className="form-message">{error}</p>}</form>
 {known&&<div className="glass known-context"><span className="eyebrow">ALREADY KNOWN, NOT RE-ENTERED</span><h2>Your verified financial context</h2><dl><div><dt>Income</dt><dd>{money(known.monthly_income)}</dd></div><div><dt>Existing EMI</dt><dd>{money(known.existing_emi)}</dd></div><div><dt>Monthly surplus</dt><dd>{money(known.monthly_surplus)}</dd></div><div><dt>Financial stress</dt><dd>{known.financial_stress.stress_level} · {known.financial_stress.stress_score}/100</dd></div><div><dt>Profile</dt><dd>{known.financial_profile.segment}</dd></div></dl><Link to="/chat"><MessageCircle size={16}/>Ask Saathi in your language</Link></div>}</section>
 {result&&<section className={`glass journey-result impact-${result.impact_level.toLowerCase().replace(' ','-')}`}><div><span className="eyebrow">FINANCIAL SUITABILITY GUIDANCE</span><h2>{result.impact_level}</h2><p>{result.recommendation}</p></div><div className="journey-flow"><span>Current surplus<strong>{money(result.current_financial_snapshot.monthly_surplus)}</strong><small>EMI burden {result.current_financial_snapshot.emi_burden_pct}% · Stress {known.financial_stress.stress_level}</small></span><ArrowRight/><span>Potential EMI<strong>{money(result.emi)}</strong><small>Impact {result.impact_level}</small></span><ArrowRight/><span>After-loan surplus<strong>{money(result.projected_financial_snapshot.monthly_surplus)}</strong><small>EMI burden {result.projected_financial_snapshot.emi_burden_pct}%</small></span></div><details><summary>Why this guidance?</summary>{result.key_impacts.map(item=><p key={item}>{item}</p>)}</details>{result.risk_factors.length>0&&<div className="why-not"><TriangleAlert/><div><strong>Why NOT this right now?</strong>{result.risk_factors.map(item=><p key={item}>{item}</p>)}</div></div>}<div className="safer-copy"><CheckCircle2/><div><strong>Safer alternatives</strong>{result.safer_alternative.map(item=><p key={item}>{item}</p>)}</div></div><div className="result-actions"><Link to="/chat"><MessageCircle size={16}/>Ask Saathi why</Link><Link to="/recommendations">See safer alternatives <ArrowRight size={16}/></Link></div><small>{result.disclaimer}</small></section>}
 </>;
}
