import React from 'react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, ShieldCheck, Eye, EyeOff, TrendingUp } from 'lucide-react';
import Brand from '../components/ui/Brand';
import { login, saveSession } from '../services/auth';
export default function Login() {
 const [visible,setVisible] = useState(false), [message,setMessage] = useState('');
 const navigate = useNavigate();
 const submit = async e => { e.preventDefault(); const form=new FormData(e.currentTarget); try { const result=await login({email:form.get('email'),password:form.get('password')}); saveSession(result); navigate(result.onboarding_complete ? '/dashboard' : '/onboarding'); } catch(error) { setMessage(error.message); } };
 const useDemo = async id => { try { const result=await login({email:`${id.toLowerCase()}@demo.paisasaathi.local`,password:`Paisa@${id}`}); saveSession(result); navigate('/dashboard'); } catch(error) { setMessage('Demo accounts need seeding first. '+error.message); } };
 return <div className="login-page"><section className="login-story"><Brand/><div className="login-intro"><span className="eyebrow">A MORE PERSONAL WAY TO BANK</span><h1>Banking that<br/>understands <em>you.</em></h1><p>Personalized financial guidance built around your needs, goals, and financial journey.</p><div className="glass login-preview"><span className="sparkle-box"><TrendingUp/></span><div><small>YOUR NEXT CHAPTER</small><strong>More clarity. More confidence.</strong><p>Your Money, Your Needs, Your Saathi.</p></div></div></div><small className="login-credit">Made for Bharat. Built by Quantum Crew.</small></section><section className="login-form-side"><div className="glass login-card"><span className="eyebrow">YOUR JOURNEY STARTS HERE</span><h2>Welcome back.</h2><p>A clearer picture of your money awaits.</p><form onSubmit={submit}><label htmlFor="identity">Email</label><input id="identity" name="email" autoComplete="username" placeholder="you@example.com" required/><label htmlFor="password">Password</label><div className="password-field"><input id="password" name="password" type={visible ? 'text' : 'password'} autoComplete="current-password" required/><button type="button" aria-label={visible ? 'Hide password' : 'Show password'} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div><button className="primary-button" type="submit">Log in <ArrowRight size={18}/></button>{message && <p className="form-message" role="status">{message}</p>}</form><p className="login-note">New here? <a href="/register">Create your account</a></p><div className="divider"><span>DEMO ACCOUNTS · SYNTHETIC DATA ONLY</span></div><div className="quick-actions"><button className="glass-button" onClick={()=>useDemo('PS001')}>Rahul · Growth</button><button className="glass-button" onClick={()=>useDemo('PS003')}>Ramesh · Caution</button><button className="glass-button" onClick={()=>useDemo('PS004')}>Aman · Support</button></div><p className="login-note"><ShieldCheck size={16}/> Demo accounts use the normal login API and require seeding.</p></div></section></div>;
}


