import React,{useEffect,useState} from 'react';
import {Scale,ShieldCheck} from 'lucide-react';
import DataState from '../components/common/DataState';
import {getPrivacy,getResponsibleAI,updatePrivacy} from '../services/api';

export default function ResponsibleAI(){
 const [privacy,setPrivacy]=useState(null),[ai,setAI]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;const controller=new AbortController();Promise.all([getPrivacy({signal:controller.signal}),getResponsibleAI({signal:controller.signal})]).then(([p,r])=>{if(active){setPrivacy(p);setAI(r)}}).catch(err=>{if(active)setError(err.message)});return()=>{active=false;controller.abort()}},[]);
 const toggle=async key=>{const controls={...privacy.controls,[key]:!privacy.controls[key]};setPrivacy({...privacy,controls});try{await updatePrivacy(controls)}catch(err){setError(err.message)}};
 if(!privacy||!ai)return <DataState status={error?'error':'loading'}/>;
 return <><div className="page-heading"><div><span className="eyebrow">TRUST BY DESIGN</span><h1>Privacy & Responsible AI</h1><p>Transparent controls and customer-first safeguards for this prototype.</p></div><Scale/></div><div className="prototype-banner">{privacy.prototype_notice}</div><section className="trust-overview"><article className="glass"><span>1</span><h3>Your Data</h3><p>{privacy.data_used.join(', ')}.</p></article><article className="glass"><span>2</span><h3>Why We Use It</h3><p>{privacy.purpose}</p></article><article className="glass"><span>3</span><h3>Your Controls</h3><p>Turn each personalization purpose on or off below.</p></article></section><section className="responsible-grid"><div className="glass privacy-panel"><span className="eyebrow">CUSTOMER CONTROL</span><h2>Personalization controls</h2>{Object.entries(privacy.controls).map(([key,value])=><button className="consent-row" key={key} onClick={()=>toggle(key)}><span>{key.replaceAll('_',' ')}</span><b className={value?'on':''}>{value?'ON':'OFF'}</b></button>)}</div><div className="principle-grid">{ai.principles.map((item,index)=><article className="glass" key={item.name}><ShieldCheck/><strong>{index===0?'4 · ':index===1?'5 · Explainable AI · ':index===2?'6 · No Predatory Nudging · ':''}{item.name}</strong><p>{item.detail}</p></article>)}</div></section><section className="glass fairness-panel"><span className="eyebrow">FAIRNESS GUARDRAILS</span><h2>Fairness: relevant financial signals—not protected attributes.</h2><div>{ai.fairness_guardrails.map(item=><span key={item}>{item}</span>)}</div><p>{ai.fairness_note}</p><details><summary>7 · Prototype regulatory readiness</summary><ul>{ai.regulatory_readiness.map(item=><li key={item}>{item}</li>)}</ul><p>{ai.claim}</p></details></section>{error&&<p className="form-message">{error}</p>}</>;
}
